name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Push Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      DOCKER_BUILDKIT: 0

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/ccna-platform-backend:latest \
            -t ghcr.io/${{ github.repository_owner }}/ccna-platform-backend:${{ github.sha }} \
            ./backend

      - name: Push backend
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ccna-platform-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/ccna-platform-backend:${{ github.sha }}

      - name: Build frontend
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/ccna-platform-frontend:latest \
            -t ghcr.io/${{ github.repository_owner }}/ccna-platform-frontend:${{ github.sha }} \
            --build-arg NEXT_PUBLIC_API_URL=https://hntuan7684.id.vn/api/v1 \
            ./frontend

      - name: Push frontend
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ccna-platform-frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/ccna-platform-frontend:${{ github.sha }}